CREATE TABLE users(
  "userId" SERIAL PRIMARY KEY,
  "role" VARCHAR(16) DEFAULT 'user',
  "username" VARCHAR(32) UNIQUE NOT NULL,
  "password" VARCHAR(128) NOT NULL,
  "isVoted" BOOLEAN DEFAULT FALSE,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parties(
  "partyId" SERIAL PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "score" INT DEFAULT 0,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE votes(
  "voteId" SERIAL PRIMARY KEY,
  "partyId" INT NOT NULL,
  "hash" VARCHAR(512) NOT NULL,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.votes ADD FOREIGN KEY("partyId") REFERENCES public.parties("partyId");
